eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

server:
    port: 8082
spring:
    application:
        name: reservation-service
    redis:
      host: 10.120.31.186
    cloud:
        config:
            uri: http://localhost:8888
        stream:
            bindings:
                input:
                    content-type: application/json
                    destination: ticktock
                    group: custom-group
            kafka:
                binder:
                    brokers: 10.120.31.186
                    zkNodes: 10.120.31.186
