logging:
    level:
        org:
            springframework:
                security: DEBUG
server:
    port: 8086
spring:
    application:
        name: oauth2-authserver

security:
    user:
        password: password