spring:
  jpa:
    show-sql: true
  messages:
    basename: i18n/messages
    fallbackToSystemLocale: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  thymeleaf:
    cache: false
#logging.level.org.hibernate.type: TRACE


