spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://10.122.12.27:3306/test?createDatabaseIfNotExist=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: create
        show-sql: true