spring:
  jpa:
    show-sql: true
  velocity:
    dateToolAttribute: dateTool
    numberToolAttribute: numberTool
    requestContextAttribute: request
    expose-session-attributes: true
    expose-request-attributes: true
    toolbox-config-location: velocity-tools.xml
server.contextPath: /test

#logging.level.org.hibernate.type: TRACE



