INSERT INTO ROLES(ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLES(ID, ROLE_NAME) VALUES (2, 'ROLE_USER');
INSERT INTO USERS (ID, EMAIL, ENABLED, PASSWORD, USER_NAME) VALUES (1, 'admin@lenovo.com', TRUE, 'admin', 'admin');
INSERT INTO USERS (ID, EMAIL, ENABLED, PASSWORD, USER_NAME) VALUES (2, 'user@lenovo.com', TRUE, 'user', 'user');
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO PERMISSIONS(ID, DESCRIPTION, PERMISSION_NAME) VALUES (1, 'News List', 'NEWS_LIST_GET');
INSERT INTO ROLE_PERMISSIONS(PERMISSION_ID, ROLE_ID) VALUES  (1, 1);
INSERT INTO ROLE_PERMISSIONS(PERMISSION_ID, ROLE_ID) VALUES  (1, 2);