INSERT INTO USERS (ID, EMAIL, ENABLED, PASSWORD, USER_NAME) VALUES (1, 'admin@lenovo.com', TRUE, 'admin', 'admin');
INSERT INTO PUBLIC.ROLES(ID, ROLE_NAME) VALUES (1, 'ADMIN');
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);